---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - infrastructure.s4t.example.com
  resources:
  - boards
  - plugins
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - infrastructure.s4t.example.com
  resources:
  - boards/finalizers
  - plugins/finalizers
  - services/finalizers
  verbs:
  - update
- apiGroups:
  - infrastructure.s4t.example.com
  resources:
  - boards/status
  - plugins/status
  - services/status
  verbs:
  - get
  - patch
  - update
