apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: plugin.s4t.com
spec:
  group: s4t.com
  names:
    kind: Plugin
    listKind: PluginList
    plural: plugins
    singular: plugin
    shortNames:
    - plg
  scope: Namespaced
  versions:
  - name: v1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            plugin: 
            properties:
              plugin:
                type: object
                properties:
                  UUID:
                    type: string
                  port:
                    type: integer
                  protocol:
                    type: string
                  links:
                    type: array
                    items:
                      type: object
                      x-kubernetes-preserve-unknown-fields: true
          status:
            type: object
            properties:
              port:
                type: integer
              UUID:
                type: string
    subresources:
      status: {}
    additionalPrinterColumns:
    - name: Status
      type: string
      jsonPath: .status.status
    - name: Agent
      type: string
